# Generated by Django 5.2.11 on 2026-09-19 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('categoria', models.CharField(choices=[('retorica', 'Retórica'), ('fonetica_fonologia', 'Fonética y Fonología'), ('morfologia', 'Morfología'), ('sintaxis', 'Sintaxis'), ('semantica', 'Semántica'), ('linguistica', 'Lingüística'), ('ortografia', 'Ortografía'), ('redaccion', 'Redacción'), ('literatura', 'Literatura'), ('idiomas', 'Idiomas'), ('docencia', 'Docencia'), ('historia_lengua', 'Historia de la lengua'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('bachillerato', 'Bachillerato'), ('universitario', 'Universitario'), ('concurso', 'Concurso docente'), ('general', 'General')], default='general', max_length=20)),
                ('tipo_estructura', models.CharField(help_text='dict_con_tecnicas, lista_plana, lista_bilingue', max_length=30)),
                ('total_declarado', models.PositiveIntegerField(default=0)),
                ('total_real', models.PositiveIntegerField(default=0)),
                ('bilingue', models.BooleanField(default=False)),
                ('archivo_origen', models.CharField(blank=True, max_length=500)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=300)),
                ('categoria_interna', models.CharField(blank=True, max_length=200)),
                ('teoria', models.TextField(blank=True)),
                ('ejemplo', models.TextField(blank=True)),
                ('ejercicio', models.TextField(blank=True)),
                ('respuesta', models.TextField(blank=True)),
                ('titulo_en', models.CharField(blank=True, max_length=300)),
                ('teoria_en', models.TextField(blank=True)),
                ('ejemplo_en', models.TextField(blank=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='contenido.recurso')),
            ],
            options={
                'verbose_name': 'Técnica',
                'verbose_name_plural': 'Técnicas',
                'ordering': ['recurso', 'numero'],
                'unique_together': {('recurso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_tecnicas', to=settings.AUTH_USER_MODEL)),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.tecnica')),
            ],
            options={
                'unique_together': {('usuario', 'tecnica')},
            },
        ),
    ]
