# Generated by Django 5.2.11 on 2026-09-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlInteractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('categoria', models.CharField(choices=[('retorica', 'Retórica'), ('fonetica_fonologia', 'Fonética y Fonología'), ('morfologia', 'Morfología'), ('sintaxis', 'Sintaxis'), ('semantica', 'Semántica'), ('linguistica', 'Lingüística'), ('ortografia', 'Ortografía'), ('redaccion', 'Redacción'), ('literatura', 'Literatura'), ('idiomas', 'Idiomas'), ('docencia', 'Docencia'), ('historia_lengua', 'Historia de la lengua'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('tipo', models.CharField(choices=[('flota', 'Flota'), ('cuaderno', 'Cuaderno'), ('juego', 'Juego'), ('archivo_vector', 'Archivo de Vector'), ('app', 'App interactiva'), ('cuaderno_ejercicios', 'Cuaderno de ejercicios'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('bachillerato', 'Bachillerato'), ('universitario', 'Universitario'), ('concurso', 'Concurso docente'), ('general', 'General')], default='general', max_length=20)),
                ('num_tecnicas', models.PositiveIntegerField(default=0)),
                ('archivo_original', models.CharField(blank=True, max_length=500)),
                ('archivo_static', models.CharField(blank=True, max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HTML interactivo',
                'verbose_name_plural': 'HTMLs interactivos',
                'ordering': ['categoria', 'tipo', 'titulo'],
            },
        ),
    ]
