# Generated by Django 5.2.11 on 2026-09-19 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0005_alter_curso_id_alter_exercise_id_alter_idioma_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecciones_minimas_pct', models.PositiveIntegerField(default=100, help_text='% mínimo de lecciones completadas (0-100)')),
                ('nota_minima', models.PositiveIntegerField(default=70, help_text='Nota mínima (0-100)')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_certificado', to='academia.curso')),
            ],
            options={
                'verbose_name': 'Requisito de certificado',
                'verbose_name_plural': 'Requisitos de certificados',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único de verificación', unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('nota_final', models.PositiveIntegerField(default=100, help_text='Nota final del curso (0-100)')),
                ('horas', models.PositiveIntegerField(default=40, help_text='Horas lectivas del curso')),
                ('pdf', models.FileField(blank=True, help_text='PDF del certificado (opcional)', null=True, upload_to='certificados/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='academia.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
