# Generated by Django 5.2.11 on 2026-09-20 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='cargo_admin',
            field=models.CharField(blank=True, default='Director General', max_length=100),
        ),
        migrations.AddField(
            model_name='certificado',
            name='cargo_profesor',
            field=models.CharField(blank=True, default='Profesor Titular', max_length=100),
        ),
        migrations.AddField(
            model_name='certificado',
            name='firmado_por_admin',
            field=models.ForeignKey(blank=True, help_text='Administrador que firma el certificado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_firmados_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='firmado_por_profesor',
            field=models.ForeignKey(blank=True, help_text='Profesor que firma el certificado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_firmados_profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='institucion',
            field=models.CharField(default='Academia Global de Castellano', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='horas',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nota_final',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='requisitocertificado',
            name='lecciones_minimas_pct',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='requisitocertificado',
            name='nota_minima',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Profesor', help_text='Cargo que aparece bajo la firma (ej. Director, Profesor Titular)', max_length=100)),
                ('institucion', models.CharField(default='Academia Global de Castellano', max_length=200)),
                ('firma_imagen', models.CharField(blank=True, help_text='Ruta al archivo de imagen de la firma (opcional)', max_length=500)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_certificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
            },
        ),
    ]
