# Generated by Django 6.0.1 on 2026-01-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0002_leccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('completar', 'Completar'), ('vf', 'Verdadero / Falso'), ('ordenar', 'Ordenar'), ('relacionar', 'Relacionar')], max_length=30)),
                ('enunciado', models.TextField()),
                ('datos', models.JSONField(help_text='Configuración dinámica del ejercicio')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='academia.leccion')),
            ],
        ),
    ]
