# Generated by Django 5.2.11 on 2026-09-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_alter_ejercicio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
