# Generated by Django 5.2.11 on 2026-09-19 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_curso_id_alter_exercise_id_alter_idioma_id_and_more'),
        ('ejercicios', '0003_alter_ejercicio_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('num_preguntas', models.PositiveIntegerField(default=10)),
                ('nota_minima', models.PositiveIntegerField(default=70)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academia.curso')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='ejercicios.evaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_evaluacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de evaluación',
                'verbose_name_plural': 'Intentos de evaluación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('enunciado', models.TextField()),
                ('opciones', models.JSONField(default=list, help_text="Lista de opciones: ['A', 'B', 'C', 'D']")),
                ('respuesta_correcta', models.CharField(max_length=500)),
                ('explicacion', models.TextField(blank=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ejercicios.evaluacion')),
            ],
            options={
                'ordering': ['evaluacion', 'orden'],
                'unique_together': {('evaluacion', 'orden')},
            },
        ),
    ]
