# Generated by Django 6.0.1 on 2026-01-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden pedagógico dentro del curso')),
                ('contenido', models.TextField(help_text='Contenido principal de la lección')),
                ('activa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='academia.curso')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('curso', 'orden')},
            },
        ),
    ]
