# Generated by Django 5.2.11 on 2026-09-19 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏅', max_length=10)),
                ('tipo', models.CharField(choices=[('estrella', '⭐ Estrella'), ('medalla', '🏅 Medalla'), ('libro', '📚 Libro'), ('trofeo', '🏆 Trofeo'), ('corona', '👑 Corona')], default='medalla', max_length=20)),
                ('requisito_xp', models.PositiveIntegerField(default=0)),
                ('requisito_cursos', models.PositiveIntegerField(default=0)),
                ('requisito_lecciones', models.PositiveIntegerField(default=0)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGamificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('nivel_actual', models.PositiveIntegerField(default=1)),
                ('racha_dias', models.PositiveIntegerField(default=0)),
                ('cursos_completados', models.PositiveIntegerField(default=0)),
                ('lecciones_completadas', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacion.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
